//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplication
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Addres { get; set; }
        public string Gender { get; set; }
        public string Picture { get; set; }
        public string Tc { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string Experience { get; set; }
        public string Education { get; set; }
        public Nullable<int> GovernanceID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual Governance Governance { get; set; }
    }
}
