//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int ProductID { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string BarcodeNo { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public string DateTimee { get; set; }
    }
}
